#topic: img.dvr
model: /home/joao/Downloads/ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb
#model: /home/josias/vision/tensorflow/models/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03/frozen_inference_graph.pb
#model: /home/josias/vision/tensorflow/models/faster_rcnn_resnet50_coco_2018_01_28/frozen_inference_graph.pb
labels: /home/joao/repositories/opencv_rtsp/labels/ssd_inception_labels.csv
#rtsp_url: rtsp://172.16.165.133:8554/
rtsp_url: rtsp://172.16.165.151:8554/
#rtsp_url: rtsp://localhost:8554/
out_fps: 1
movie: true
still_image: /home/joao/repositories/opencv_rtsp/images/test2.bmp
#still_image: /home/josias/workspace/IdeaProjects/rust/opencv_rtsp/images/test2.bmp